### ISSUE TITLE
Exception : [std::bad_alloc]  / alevin was invoked improperly in HPC Cluster

### ISSUE THREAD

**Issue by ebecht** [COMBINE-lab/salmon#328]
Hi and thank you for helping,

**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
alevin

**Describe the bug**
Running alevin on 10x v1 data results in the following error:
> [alevinLog] [info] Starting Import of the gene count matrix.
> Exception : [std::bad_alloc]
>  alevin was invoked improperly

**To Reproduce**

  * Salmon version: Release v0.11.3
  * Installed from: Compiled. I also followed the instructions from the [alevin tutorial](https://combine-lab.github.io/alevin-tutorial/2018/running-alevin/) to compile the `scripts/v1_10x/wrapper.cpp` file
  * Reference transcriptome: [Homo_sapiens.GRCh37.cdna.all.fa](ftp://ftp.ensembl.org/pub/grch37/release-83/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh37.cdna.all.fa.gz)
  * Which read files were used? Either the [CD14+ Monocytes from the 10x v1 paper](http://s3-us-west-2.amazonaws.com/10x.files/samples/cell-exp/1.1.0/cd14_monocytes/cd14_monocytes_fastqs.tar) or the [PBMC 3k from the same paper](http://cf.10xgenomics.com/samples/cell-exp/1.0.0/pbmc3k/pbmc3k_fastqs.tar)
  * Which program options were used?
I ran the following command for the CD14 Monocytes dataset:
`~/software/salmon/scripts/v1_10x/run.sh ~/software/salmon/bin/salmon salmon alevin -l ISR -b ./fastq/fastqs/flowcell1/ --gemcode -i ./transcripts_index_salmon/ -p 8 -o ./fastq/test/ --tgMap ./hg_transcriptome/tx2tx.tsv --end 5 --umiLength 5 --barcodeLength 14 --dumpCsvCounts
`
and the following one for the PBMC_3K dataset:
`~/software/salmon/scripts/v1_10x/run.sh ~/software/salmon/bin/salmon alevin -l ISR -b pbmc3k_fastqs/ --gemcode -i ../transcripts_index_salmon/ -p 8 -o alevin_output --tgMap ../hg_transcriptome/tx2gene.tsv --dumpCsvCounts
`

**Screenshots**
CD14+ Monocytes shell log:
```~/software/salmon/scripts/v1_10x/run.sh salmon alevin -l ISR -b ./fastqs/flowcell1/ --gemcode -i ../transcripts_index_salmon/ -p 8 -o ./fastq/test/ --tgMap ../hg_transcriptome/tx2tx.tsv --end 5 --umiLength 5 --barcodeLength 14 --dumpCsvCounts --dumpFeatures

TEMPDIR is /tmp/tmp.lLLibfwH4G
Running command [salmon alevin -l ISR  --gemcode -i ../transcripts_index_salmon/ -p 8 -o ./fastq/test/ --tgMap ../hg_transcriptome/tx2tx.tsv --end 5 --umiLength 5 --barcodeLength 14 --dumpCsvCounts --dumpFeatures -1 /tmp/tmp.lLLibfwH4G/p1.fa -2 /tmp/tmp.lLLibfwH4G/p2.fa -r ./fastqs/flowcell1/read-I1_si-ACTTCACT_lane-001-chunk-001.fastq.gz
./fastqs/flowcell1/read-I1_si-ACTTCACT_lane-002-chunk-000.fastq.gz
./fastqs/flowcell1/read-I1_si-ACTTCACT_lane-003-chunk-003.fastq.gz
./fastqs/flowcell1/read-I1_si-ACTTCACT_lane-004-chunk-002.fastq.gz
./fastqs/flowcell1/read-I1_si-CGAAGTTG_lane-001-chunk-001.fastq.gz
./fastqs/flowcell1/read-I1_si-CGAAGTTG_lane-002-chunk-000.fastq.gz
./fastqs/flowcell1/read-I1_si-CGAAGTTG_lane-003-chunk-003.fastq.gz
./fastqs/flowcell1/read-I1_si-CGAAGTTG_lane-004-chunk-002.fastq.gz
./fastqs/flowcell1/read-I1_si-GAGCACGC_lane-001-chunk-001.fastq.gz
./fastqs/flowcell1/read-I1_si-GAGCACGC_lane-002-chunk-000.fastq.gz
./fastqs/flowcell1/read-I1_si-GAGCACGC_lane-003-chunk-003.fastq.gz
./fastqs/flowcell1/read-I1_si-GAGCACGC_lane-004-chunk-002.fastq.gz
./fastqs/flowcell1/read-I1_si-TTCGTGAA_lane-001-chunk-001.fastq.gz
./fastqs/flowcell1/read-I1_si-TTCGTGAA_lane-002-chunk-000.fastq.gz
./fastqs/flowcell1/read-I1_si-TTCGTGAA_lane-003-chunk-003.fastq.gz
./fastqs/flowcell1/read-I1_si-TTCGTGAA_lane-004-chunk-002.fastq.gz]
Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at https://combine-lab.github.io/salmon
[2018-12-05 15:10:07.252] [alevinLog] [info] A custom protocol (END, BC length, UMI length) = (5, 14, 5) is being used.  Updating UMI k-mer length accordingly.
Logs will be written to ./fastq/test/logs
### alevin (dscRNA-seq quantification) v0.11.3
### [ program ] => salmon 
### [ command ] => alevin 
### [ libType ] => { ISR }
### [ gemcode ] => { }
### [ index ] => { ../transcripts_index_salmon/ }
### [ threads ] => { 8 }
### [ output ] => { ./fastq/test/ }
### [ tgMap ] => { ../hg_transcriptome/tx2tx.tsv }
### [ end ] => { 5 }
### [ umiLength ] => { 5 }
### [ barcodeLength ] => { 14 }
### [ dumpCsvCounts ] => { }
### [ dumpFeatures ] => { }
### [ mates1 ] => { /tmp/tmp.lLLibfwH4G/p1.fa }
### [ mates2 ] => { /tmp/tmp.lLLibfwH4G/p2.fa }
### [ unmatedReads ] => { ./fastqs/flowcell1/read-I1_si-ACTTCACT_lane-001-chunk-001.fastq.gz ./fastqs/flowcell1/read-I1_si-ACTTCACT_lane-002-chunk-000.fastq.gz ./fastqs/flowcell1/read-I1_si-ACTTCACT_lane-003-chunk-003.fastq.gz ./fastqs/flowcell1/read-I1_si-ACTTCACT_lane-004-chunk-002.fastq.gz ./fastqs/flowcell1/read-I1_si-CGAAGTTG_lane-001-chunk-001.fastq.gz ./fastqs/flowcell1/read-I1_si-CGAAGTTG_lane-002-chunk-000.fastq.gz ./fastqs/flowcell1/read-I1_si-CGAAGTTG_lane-003-chunk-003.fastq.gz ./fastqs/flowcell1/read-I1_si-CGAAGTTG_lane-004-chunk-002.fastq.gz ./fastqs/flowcell1/read-I1_si-GAGCACGC_lane-001-chunk-001.fastq.gz ./fastqs/flowcell1/read-I1_si-GAGCACGC_lane-002-chunk-000.fastq.gz ./fastqs/flowcell1/read-I1_si-GAGCACGC_lane-003-chunk-003.fastq.gz ./fastqs/flowcell1/read-I1_si-GAGCACGC_lane-004-chunk-002.fastq.gz ./fastqs/flowcell1/read-I1_si-TTCGTGAA_lane-001-chunk-001.fastq.gz ./fastqs/flowcell1/read-I1_si-TTCGTGAA_lane-002-chunk-000.fastq.gz ./fastqs/flowcell1/read-I1_si-TTCGTGAA_lane-003-chunk-003.fastq.gz ./fastqs/flowcell1/read-I1_si-TTCGTGAA_lane-004-chunk-002.fastq.gz }


[2018-12-05 15:10:07.288] [jointLog] [info] Fragment incompatibility prior below threshold.  Incompatible fragments will be ignored.
[2018-12-05 15:10:07.288] [jointLog] [warning] You seem to have passed in both un-paired reads and paired-end reads. It is not currently possible to quantify hybrid library types in salmon.
[2018-12-05 15:10:07.298] [alevinLog] [info] Processing barcodes files (if Present) 

 
processed 267 Million barcodes

[2018-12-05 15:12:18.914] [alevinLog] [info] Done barcode density calculation.
[2018-12-05 15:12:18.914] [alevinLog] [info] # Barcodes Used: 267451749 / 267548197.
[2018-12-05 15:12:25.126] [alevinLog] [info] Knee found left boundary at  11954 
[2018-12-05 15:12:27.371] [alevinLog] [info] Gauss Corrected Boundary at  4345 
[2018-12-05 15:12:27.371] [alevinLog] [info] Learned InvCov: 713.683 normfactor: 1183.93
[2018-12-05 15:12:27.371] [alevinLog] [info] Total 5344(has 999 low confidence) barcodes
[2018-12-05 15:12:27.494] [alevinLog] [info] Done True Barcode Sampling
[2018-12-05 15:12:27.880] [alevinLog] [info] Done populating Z matrix
[2018-12-05 15:12:27.952] [alevinLog] [info] Done indexing Barcodes
[2018-12-05 15:12:27.952] [alevinLog] [info] Total Unique barcodes found: 4180559
[2018-12-05 15:12:27.952] [alevinLog] [info] Used Barcodes except Whitelist: 134856
[2018-12-05 15:12:29.321] [stderrLog] [info] Loading Suffix Array 
[2018-12-05 15:12:29.216] [jointLog] [info] There are 2 libraries.
[2018-12-05 15:12:29.318] [jointLog] [info] Loading Quasi index
[2018-12-05 15:12:29.319] [jointLog] [info] Loading 32-bit quasi index
[2018-12-05 15:12:29.216] [alevinLog] [info] Done with Barcode Processing; Moving to Quantify

[2018-12-05 15:12:29.216] [alevinLog] [info] parsing read library format
[2018-12-05 15:12:29.949] [stderrLog] [info] Loading Transcript Info 
[2018-12-05 15:12:30.141] [stderrLog] [info] Loading Rank-Select Bit Array
[2018-12-05 15:12:30.181] [stderrLog] [info] There were 167,268 set bits in the bit array
[2018-12-05 15:12:30.197] [stderrLog] [info] Computing transcript lengths
[2018-12-05 15:12:30.197] [stderrLog] [info] Waiting to finish loading hash
[2018-12-05 15:12:34.297] [stderrLog] [info] Done loading index
[2018-12-05 15:12:34.297] [jointLog] [info] done
[2018-12-05 15:12:34.297] [jointLog] [info] Index contained 167,268 targets



processed 267 Million fragments
hits: 892324990, hits per frag:  3.33692



[2018-12-05 15:45:46.198] [jointLog] [info] Computed 185,593 rich equivalence classes for further processing
[2018-12-05 15:45:46.198] [jointLog] [info] Counted 163,106,139 total reads in the equivalence classes 
[2018-12-05 15:45:46.199] [jointLog] [warning] Found 115077 reads with `N` in the UMI sequence and ignored the reads.
Please report on github if this number is too large
[2018-12-05 15:45:46.199] [jointLog] [info] Mapping rate = 60.9633%

[2018-12-05 15:45:46.199] [jointLog] [info] finished quantifyLibrary()
[2018-12-05 15:45:47.617] [alevinLog] [info] Starting optimizer

Analyzed 5344 cells (100% of all).
[2018-12-05 15:47:14.597] [alevinLog] [info] Total 1870793 UMI after deduplicating.
[2018-12-05 15:47:14.693] [alevinLog] [info] Clearing EqMap; Might take some time.
[2018-12-05 15:47:18.921] [alevinLog] [info] Starting Import of the gene count matrix.
Exception : [std::bad_alloc]
 alevin was invoked improperly.
For usage information, try  alevin --help
Exiting.
```

PBMC 3k shell log:
```
~/software/salmon/scripts/v1_10x/run.sh salmon alevin -lISR -b pbmc3k_fastqs/ --gemcode -i ../transcripts_index_salmon/ -p 8 -o alevin_output --tgMap ../hg_transcriptome/tx2gene.tsv

TEMPDIR is /tmp/tmp.WnzMm7GQBO
Running command [salmon alevin -lISR  --gemcode -i ../transcripts_index_salmon/ -p 8 -o alevin_output --tgMap ../hg_transcriptome/tx2gene.tsv -1 /tmp/tmp.WnzMm7GQBO/p1.fa -2 /tmp/tmp.WnzMm7GQBO/p2.fa -r pbmc3k_fastqs/read-I1_si-ACGCGGAA_lane-001-chunk-001.fastq.gz
pbmc3k_fastqs/read-I1_si-ACGCGGAA_lane-002-chunk-000.fastq.gz
pbmc3k_fastqs/read-I1_si-CGCTATCC_lane-001-chunk-001.fastq.gz
pbmc3k_fastqs/read-I1_si-CGCTATCC_lane-002-chunk-000.fastq.gz
pbmc3k_fastqs/read-I1_si-GTTGCATG_lane-001-chunk-001.fastq.gz
pbmc3k_fastqs/read-I1_si-GTTGCATG_lane-002-chunk-000.fastq.gz
pbmc3k_fastqs/read-I1_si-TAAATCGT_lane-001-chunk-001.fastq.gz
pbmc3k_fastqs/read-I1_si-TAAATCGT_lane-002-chunk-000.fastq.gz]
Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at https://combine-lab.github.io/salmon
Logs will be written to alevin_output/logs
### alevin (dscRNA-seq quantification) v0.11.3
### [ program ] => salmon 
### [ command ] => alevin 
### [ libType ] => { ISR }
### [ gemcode ] => { }
### [ index ] => { ../transcripts_index_salmon/ }
### [ threads ] => { 8 }
### [ output ] => { alevin_output }
### [ tgMap ] => { ../hg_transcriptome/tx2gene.tsv }
### [ mates1 ] => { /tmp/tmp.WnzMm7GQBO/p1.fa }
### [ mates2 ] => { /tmp/tmp.WnzMm7GQBO/p2.fa }
### [ unmatedReads ] => { pbmc3k_fastqs/read-I1_si-ACGCGGAA_lane-001-chunk-001.fastq.gz pbmc3k_fastqs/read-I1_si-ACGCGGAA_lane-002-chunk-000.fastq.gz pbmc3k_fastqs/read-I1_si-CGCTATCC_lane-001-chunk-001.fastq.gz pbmc3k_fastqs/read-I1_si-CGCTATCC_lane-002-chunk-000.fastq.gz pbmc3k_fastqs/read-I1_si-GTTGCATG_lane-001-chunk-001.fastq.gz pbmc3k_fastqs/read-I1_si-GTTGCATG_lane-002-chunk-000.fastq.gz pbmc3k_fastqs/read-I1_si-TAAATCGT_lane-001-chunk-001.fastq.gz pbmc3k_fastqs/read-I1_si-TAAATCGT_lane-002-chunk-000.fastq.gz }


[2018-12-05 16:30:15.406] [jointLog] [info] Fragment incompatibility prior below threshold.  Incompatible fragments will be ignored.
[2018-12-05 16:30:15.406] [jointLog] [warning] You seem to have passed in both un-paired reads and paired-end reads. It is not currently possible to quantify hybrid library types in salmon.
[2018-12-05 16:30:15.416] [alevinLog] [info] Processing barcodes files (if Present) 

 
processed 185 Million barcodes

[2018-12-05 16:31:41.387] [alevinLog] [info] Done barcode density calculation.
[2018-12-05 16:31:41.387] [alevinLog] [info] # Barcodes Used: 185898660 / 185980783.
[2018-12-05 16:31:47.863] [alevinLog] [info] Knee found left boundary at  2926 
[2018-12-05 16:31:50.571] [alevinLog] [info] Gauss Corrected Boundary at  2858 
[2018-12-05 16:31:50.571] [alevinLog] [info] Learned InvCov: 166.8 normfactor: 2759.5
[2018-12-05 16:31:50.571] [alevinLog] [info] Total 3856(has 998 low confidence) barcodes
[2018-12-05 16:31:50.638] [alevinLog] [info] Done True Barcode Sampling
[2018-12-05 16:31:50.935] [alevinLog] [info] Done populating Z matrix
[2018-12-05 16:31:51.000] [alevinLog] [info] Done indexing Barcodes
[2018-12-05 16:31:51.000] [alevinLog] [info] Total Unique barcodes found: 3825581
[2018-12-05 16:31:51.000] [alevinLog] [info] Used Barcodes except Whitelist: 138266
[2018-12-05 16:31:51.087] [alevinLog] [info] Done with Barcode Processing; Moving to Quantify

[2018-12-05 16:31:51.087] [alevinLog] [info] parsing read library format
[2018-12-05 16:31:51.087] [jointLog] [info] There are 2 libraries.
[2018-12-05 16:31:51.161] [jointLog] [info] Loading Quasi index
[2018-12-05 16:31:51.162] [jointLog] [info] Loading 32-bit quasi index
[2018-12-05 16:31:51.164] [stderrLog] [info] Loading Suffix Array 
[2018-12-05 16:31:51.808] [stderrLog] [info] Loading Transcript Info 
[2018-12-05 16:31:51.960] [stderrLog] [info] Loading Rank-Select Bit Array
[2018-12-05 16:31:52.001] [stderrLog] [info] There were 167,268 set bits in the bit array
[2018-12-05 16:31:52.022] [stderrLog] [info] Computing transcript lengths
[2018-12-05 16:31:52.022] [stderrLog] [info] Waiting to finish loading hash
[2018-12-05 16:31:56.025] [stderrLog] [info] Done loading index
[2018-12-05 16:31:56.025] [jointLog] [info] done
[2018-12-05 16:31:56.025] [jointLog] [info] Index contained 167,268 targets



processed 185 Million fragments
hits: 690426925, hits per frag:  3.72226





[2018-12-05 16:57:31.421] [jointLog] [info] Computed 215,739 rich equivalence classes for further processing
[2018-12-05 16:57:31.421] [jointLog] [info] Counted 131,957,987 total reads in the equivalence classes 
[2018-12-05 16:57:31.421] [jointLog] [warning] 0.000112378% of fragments were shorter than the k used to build the index (31).
If this fraction is too large, consider re-building the index with a smaller k.
The minimum read size found was 24.


[2018-12-05 16:57:31.421] [jointLog] [warning] Found 539897 reads with `N` in the UMI sequence and ignored the reads.
Please report on github if this number is too large
[2018-12-05 16:57:31.421] [jointLog] [info] Mapping rate = 70.9532%

[2018-12-05 16:57:31.421] [jointLog] [info] finished quantifyLibrary()
[2018-12-05 16:57:35.529] [alevinLog] [info] Starting optimizer

Analyzed 3856 cells (100% of all).
[2018-12-05 17:04:51.878] [alevinLog] [info] Total 47125847 UMI after deduplicating.
[2018-12-05 17:04:51.928] [alevinLog] [info] Clearing EqMap; Might take some time.
[2018-12-05 17:05:04.064] [alevinLog] [info] Starting Import of the gene count matrix.
Exception : [std::bad_alloc]
 alevin was invoked improperly.
For usage information, try  alevin --help
Exiting.
```

**Desktop (please complete the following information):**
Ubuntu 14.04 LTS
3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**Additional context**
If I include only a subset of the fastq files, the command completes with no error. I have succeeded in running up to 3 of the files (3 *I1*, 3 *I2* and 3 *RA* files), but got the above-mentioned error when running it on 4 or more fastq files. I read that std::bad_alloc was usually caused by memory issues. The system I am using has 128Gb of RAM available.

Thank you for your help

**Comment by k3yavi** [comment]
Hi @ebecht ,
Can you please try running Alevin again with the latest release, we just released v0.12.0 ?

**Comment by ebecht** [comment]
Hello @k3yavi and thank you for the pointer,

I obtained the same bug with v.0.12.0 (also Compiled from source)

Here's the console log :

```
~/software/salmon/scripts/v1_10x/run.sh ~/software/salmon-0.12.0/bin/salmon alevin -l ISR -b ./fastq/fastqs/flowcell1/ --gemcode -i ./transcripts_index_salmon/ -p 8 -o ./fastq/test/ --tgMap ./hg_transcriptome/tx2tx.tsv --end 5 --umiLength 5 --barcodeLength 14 --dumpCsvCounts

TEMPDIR is /tmp/tmp.p28w2nGvAn
Running command [/home/ebecht/software/salmon-0.12.0/bin/salmon alevin -l ISR  --gemcode -i ./transcripts_index_salmon/ -p 8 -o ./fastq/test/ --tgMap ./hg_transcriptome/tx2tx.tsv --end 5 --umiLength 5 --barcodeLength 14 --dumpCsvCounts -1 /tmp/tmp.p28w2nGvAn/p1.fa -2 /tmp/tmp.p28w2nGvAn/p2.fa -r ./fastq/fastqs/flowcell1/read-I1_si-ACTTCACT_lane-001-chunk-001.fastq.gz
./fastq/fastqs/flowcell1/read-I1_si-ACTTCACT_lane-002-chunk-000.fastq.gz
./fastq/fastqs/flowcell1/read-I1_si-ACTTCACT_lane-003-chunk-003.fastq.gz
./fastq/fastqs/flowcell1/read-I1_si-ACTTCACT_lane-004-chunk-002.fastq.gz
./fastq/fastqs/flowcell1/read-I1_si-CGAAGTTG_lane-001-chunk-001.fastq.gz
./fastq/fastqs/flowcell1/read-I1_si-CGAAGTTG_lane-002-chunk-000.fastq.gz
./fastq/fastqs/flowcell1/read-I1_si-CGAAGTTG_lane-003-chunk-003.fastq.gz
./fastq/fastqs/flowcell1/read-I1_si-CGAAGTTG_lane-004-chunk-002.fastq.gz
./fastq/fastqs/flowcell1/read-I1_si-GAGCACGC_lane-001-chunk-001.fastq.gz
./fastq/fastqs/flowcell1/read-I1_si-GAGCACGC_lane-002-chunk-000.fastq.gz
./fastq/fastqs/flowcell1/read-I1_si-GAGCACGC_lane-003-chunk-003.fastq.gz
./fastq/fastqs/flowcell1/read-I1_si-GAGCACGC_lane-004-chunk-002.fastq.gz
./fastq/fastqs/flowcell1/read-I1_si-TTCGTGAA_lane-001-chunk-001.fastq.gz
./fastq/fastqs/flowcell1/read-I1_si-TTCGTGAA_lane-002-chunk-000.fastq.gz
./fastq/fastqs/flowcell1/read-I1_si-TTCGTGAA_lane-003-chunk-003.fastq.gz
./fastq/fastqs/flowcell1/read-I1_si-TTCGTGAA_lane-004-chunk-002.fastq.gz]
Version Info: This is the most recent version of salmon.
[2018-12-06 11:14:56.513] [alevinLog] [info] A custom protocol (END, BC length, UMI length) = (5, 14, 5) is being used.  Updating UMI k-mer length accordingly.
Logs will be written to ./fastq/test/logs
[2018-12-06 11:14:56.533] [jointLog] [info] Fragment incompatibility prior below threshold.  Incompatible fragments will be ignored.
### alevin (dscRNA-seq quantification) v0.12.0
### [ program ] => salmon 
### [ command ] => alevin 
### [ libType ] => { ISR }
### [ gemcode ] => { }
### [ index ] => { ./transcripts_index_salmon/ }
### [ threads ] => { 8 }
### [ output ] => { ./fastq/test/ }
### [ tgMap ] => { ./hg_transcriptome/tx2tx.tsv }
### [ end ] => { 5 }
### [ umiLength ] => { 5 }
### [ barcodeLength ] => { 14 }
### [ dumpCsvCounts ] => { }
### [ mates1 ] => { /tmp/tmp.p28w2nGvAn/p1.fa }
### [ mates2 ] => { /tmp/tmp.p28w2nGvAn/p2.fa }
### [ unmatedReads ] => { ./fastq/fastqs/flowcell1/read-I1_si-ACTTCACT_lane-001-chunk-001.fastq.gz ./fastq/fastqs/flowcell1/read-I1_si-ACTTCACT_lane-002-chunk-000.fastq.gz ./fastq/fastqs/flowcell1/read-I1_si-ACTTCACT_lane-003-chunk-003.fastq.gz ./fastq/fastqs/flowcell1/read-I1_si-ACTTCACT_lane-004-chunk-002.fastq.gz ./fastq/fastqs/flowcell1/read-I1_si-CGAAGTTG_lane-001-chunk-001.fastq.gz ./fastq/fastqs/flowcell1/read-I1_si-CGAAGTTG_lane-002-chunk-000.fastq.gz ./fastq/fastqs/flowcell1/read-I1_si-CGAAGTTG_lane-003-chunk-003.fastq.gz ./fastq/fastqs/flowcell1/read-I1_si-CGAAGTTG_lane-004-chunk-002.fastq.gz ./fastq/fastqs/flowcell1/read-I1_si-GAGCACGC_lane-001-chunk-001.fastq.gz ./fastq/fastqs/flowcell1/read-I1_si-GAGCACGC_lane-002-chunk-000.fastq.gz ./fastq/fastqs/flowcell1/read-I1_si-GAGCACGC_lane-003-chunk-003.fastq.gz ./fastq/fastqs/flowcell1/read-I1_si-GAGCACGC_lane-004-chunk-002.fastq.gz ./fastq/fastqs/flowcell1/read-I1_si-TTCGTGAA_lane-001-chunk-001.fastq.gz ./fastq/fastqs/flowcell1/read-I1_si-TTCGTGAA_lane-002-chunk-000.fastq.gz ./fastq/fastqs/flowcell1/read-I1_si-TTCGTGAA_lane-003-chunk-003.fastq.gz ./fastq/fastqs/flowcell1/read-I1_si-TTCGTGAA_lane-004-chunk-002.fastq.gz }


[2018-12-06 11:14:56.533] [jointLog] [warning] You seem to have passed in both un-paired reads and paired-end reads. It is not currently possible to quantify hybrid library types in salmon.
[2018-12-06 11:14:56.533] [jointLog] [info] Usage of --validateMappings implies use of minScoreFraction. Since not explicitly specified, it is being set to 0.65
[2018-12-06 11:14:56.533] [jointLog] [info] Usage of --validateMappings implies use of range factorization. rangeFactorizationBins is being set to 4
[2018-12-06 11:14:56.534] [jointLog] [info] Usage of --validateMappings implies a default consensus slack of 1. Setting consensusSlack to 1.
[2018-12-06 11:14:56.534] [jointLog] [info] Using default value of 0.8 for minScoreFraction in Alevin
[2018-12-06 11:14:56.540] [alevinLog] [info] Processing barcodes files (if Present) 

 
processed 267 Million barcodes

[2018-12-06 11:16:47.491] [alevinLog] [info] Done barcode density calculation.
[2018-12-06 11:16:47.491] [alevinLog] [info] # Barcodes Used: 267451749 / 267548197.
[2018-12-06 11:16:52.732] [alevinLog] [info] Knee found left boundary at  11955 
[2018-12-06 11:16:54.977] [alevinLog] [info] Gauss Corrected Boundary at  4345 
[2018-12-06 11:16:54.977] [alevinLog] [info] Learned InvCov: 713.683 normfactor: 1183.93
[2018-12-06 11:16:54.985] [alevinLog] [info] Total 31.0106% reads will be thrown away because of noisy Cellular barcodes.
[2018-12-06 11:16:54.985] [alevinLog] [info] Total 5344(has 999 low confidence) barcodes
[2018-12-06 11:16:55.059] [alevinLog] [info] Done True Barcode Sampling
[2018-12-06 11:16:55.395] [alevinLog] [info] Done populating Z matrix
[2018-12-06 11:16:55.453] [alevinLog] [info] Done indexing Barcodes
[2018-12-06 11:16:55.453] [alevinLog] [info] Total Unique barcodes found: 4180559
[2018-12-06 11:16:55.453] [alevinLog] [info] Used Barcodes except Whitelist: 134856
[2018-12-06 11:16:56.218] [jointLog] [info] There are 2 libraries.
[2018-12-06 11:16:56.292] [jointLog] [info] Loading Quasi index
[2018-12-06 11:16:56.294] [jointLog] [info] Loading 32-bit quasi index
[2018-12-06 11:16:56.205] [alevinLog] [info] Done with Barcode Processing; Moving to Quantify

[2018-12-06 11:16:56.218] [alevinLog] [info] parsing read library format
[2018-12-06 11:16:56.296] [stderrLog] [info] Loading Suffix Array 
[2018-12-06 11:16:56.846] [stderrLog] [info] Loading Transcript Info 
[2018-12-06 11:16:57.009] [stderrLog] [info] Loading Rank-Select Bit Array
[2018-12-06 11:16:57.046] [stderrLog] [info] There were 167,268 set bits in the bit array
[2018-12-06 11:16:57.063] [stderrLog] [info] Computing transcript lengths
[2018-12-06 11:16:57.064] [stderrLog] [info] Waiting to finish loading hash
[2018-12-06 11:17:00.929] [jointLog] [info] done
[2018-12-06 11:17:00.929] [jointLog] [info] Index contained 167,268 targets




processed 267 Million fragmentsrrLog] [info] Done loading index
hits: 844899161, hits per frag:  3.15864^[[D



[2018-12-06 11:45:12.188] [jointLog] [info] Computed 118,295 rich equivalence classes for further processing
[2018-12-06 11:45:12.188] [jointLog] [info] Counted 154,595,094 total reads in the equivalence classes 
[2018-12-06 11:45:12.188] [jointLog] [warning] Found 115077 reads with `N` in the UMI sequence and ignored the reads.
Please report on github if this number is too large
[2018-12-06 11:45:12.188] [jointLog] [info] Mapping rate = 57.7821%

[2018-12-06 11:45:12.188] [jointLog] [info] finished quantifyLibrary()
[2018-12-06 11:45:13.385] [alevinLog] [info] Starting optimizer

Analyzed 5344 cells (100% of all).
[2018-12-06 11:49:42.634] [alevinLog] [info] Total 4845644.00 UMI after deduplicating.
[2018-12-06 11:49:42.722] [alevinLog] [info] Clearing EqMap; Might take some time.
[2018-12-06 11:49:47.400] [alevinLog] [info] Starting Import of the gene count matrix of size 5344x167268.
Exception : [std::bad_alloc]
 alevin was invoked improperly.
For usage information, try  alevin --help
Exiting.
```

**Comment by k3yavi** [comment]
@ebecht , Thanks for confirming this.
Is it possible to rerun one more time with `--forceCells 4000`?

**Comment by k3yavi** [comment]
Also I just observed, Is it true that you have ~167k genes in your transcript to gene mapping file? That might be one of the reason since the matrix size as shown in the log is `5344x167268` and given we have doubles as the type of matrix it might add up to ~7G and possibly giving `bad_alloc`.

**Comment by ebecht** [comment]
I am trying to quantify these data at the transcript level which is why the number of features is this big. For the PBMC3k I was trying with a transcript to gene --tgMap but was still seeing the same error.

I realized I forgot to update the path to the run.sh script when calling the 0.12.0 binary (I updated the path to the binary but no to the script). When running the wrapper in the 0.12.0 folder I could succesfully run alevin on the CD14 dataset, with or without the --forceCells 4000 flag.

I tried to run alevin-0.12.0 on the PBMC 3k dataset but I got the same error. I am now trying to run it on all the FACS-sorted samples and I will see how that goes.

I feel this is happening slightly inconsistently (although very frequently). Notably, it either happens after `Clearing EqMap; Might take some time.` or `Starting Import of the gene count matrix of size 5344x167268.`. I have had it happen once in the middle of the `Analyzed xxx cells (yy% of all)` phase. I just managed to succesfully process the CD19+ B cells from the 10x v1 dataset, I'll attempt to process the other FACS sorted samples overnight and let you know how it went.

Thank you

**Comment by ebecht** [comment]
As you suggested, running alevin with a lower --forceCells parameter solved it. I'm running it with `--forceCells 500` at the moment and it's running smoothly. I am now done processing most of the datasets. I'll run the job again later and try to increase the parameter a little bit.

Thanks a lot!

**Comment by ebecht** [comment]
Hi @k3yavi,

I have some new information that may hopefully help pinpoint the source of this behavior. I managed to process 9 out of the 10 datasets I am looking at using the -forceCells 2000 option.

The only one that still fails is the CD34 subset. Interestingly, the only dataset I managed to process without seting --forceCells is the CD14 monocyte subsets.

Now that I am starting to play with the data, I realize that the number of reads per cell is way higher for the CD34 fraction, and way lower for the CD14 fraction. I am unsure what to make of it but I felt the similarity was noteworthy.

I am still trying to process the full datasets, but even by exclusively using a machine with 256Gb of RAM I was unsuccessful at it.

![alevin_readcounts_10x](https://user-images.githubusercontent.com/21232307/49974649-2a975600-feef-11e8-8cb5-1041a16d8671.png)

**Comment by k3yavi** [comment]
Hi @ebecht ,
Thanks for the plot, it's indeed very interesting.
I wonder, do you have exclusive right to the machine you are using for your experiment or is it on a cluster? If on cluster it's possible there is a different restriction on the memory usage per process/thread, I think it's worth checking that, if possible.

**Comment by ebecht** [comment]
I'm in touch with the people administrating the cluster as well and based on their guidance I ran alevin with exclusive access, however that did not help.

**Comment by k3yavi** [comment]
Just to double check and be sure, if possible, can you please run a single experiment which is failing on the cluster on a local computer with reasonable memory? 
We have seen this similar problem before and running it on a local computer worked just fine.

**Comment by ebecht** [comment]
I haven't found a desktop with enough memory to run it (the one I have access to has only 8Gb). I will try to reproduce there if I have the chance.

Have you managed to make alevin work on the sets of FASTQ I linked?

**Comment by k3yavi** [comment]
Hi @ebecht ,
Sure do let us know if it worked or not.
re FASTQ: Do you mean the pbmc3k ? Yes I was able to run Alevin to completion on the pbmc3k dataset, if that's the one you referring too?

**Comment by k3yavi** [comment]
Glad to hear that you are able to run Alevin on your personal computer. 
Do let us know if you figure out what's wrong in your cluster environment. 
We'd look into the swap issue and would post here if we observe the problem or the resolution.

**Comment by k3yavi** [comment]
Hi @ebecht ,

Thanks for raising the issue. In the latest release we have significantly modified alevin to perform online feature creation and whitelisting. We hope that this might fix the memory related issue which you were observing on the clusters. Do let us know how it worked out for you.

PS: Nice work on your recent [preprint](https://www.biorxiv.org/content/10.1101/648733v1), it raises very important questions. On the similar note, we also released a preprint today, can be found [here](https://www.biorxiv.org/content/10.1101/657874v1). Do let us know your thoughts !

**Comment by ebecht** [comment]
Thanks for the update!

I'll try out the updated version and let you know if that helped.

Your new preprint sounds very interesting, I'll give it a read

**Comment by k3yavi** [comment]
I think this should be fixed with the latest release, please feel free to reopen if you still face any issues.
